export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',

  // Payments
  PAYMENT_INIT_FAILED: 'PAYMENT_INIT_FAILED',
  PAYMENT_VERIFY_FAILED: 'PAYMENT_VERIFY_FAILED',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',
  PAYMENT_PROVIDER_UNAVAILABLE: 'PAYMENT_PROVIDER_UNAVAILABLE',
  PAYMENT_VALIDATION: 'PAYMENT_VALIDATION',

  // Checkout / Orders
  STOCK_INSUFFICIENT: 'STOCK_INSUFFICIENT',
  CART_EMPTY: 'CART_EMPTY',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  INVALID_SHIPPING_REGION: 'INVALID_SHIPPING_REGION',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ITEM_NOT_FOUND: 'ORDER_ITEM_NOT_FOUND',
  ORDER_NOTE_NOT_FOUND: 'ORDER_NOTE_NOT_FOUND',
  ORDER_NOTE_EMPTY: 'ORDER_NOTE_EMPTY',
  ORDER_QUANTITY_INVALID: 'ORDER_QUANTITY_INVALID',
  ORDER_STATE_INVALID: 'ORDER_STATE_INVALID',

  // Coupons
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_NOT_YET_VALID: 'COUPON_NOT_YET_VALID',
  COUPON_MAX_USES_REACHED: 'COUPON_MAX_USES_REACHED',
  COUPON_MIN_AMOUNT_NOT_MET: 'COUPON_MIN_AMOUNT_NOT_MET',
  COUPON_INACTIVE: 'COUPON_INACTIVE',
  COUPON_PERCENTAGE_OUT_OF_RANGE: 'COUPON_PERCENTAGE_OUT_OF_RANGE',
  COUPON_CODE_ALREADY_EXISTS: 'COUPON_CODE_ALREADY_EXISTS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
